name: Build Beamer Presentation

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install minimal TeX Live packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-latex-extra \
            texlive-lang-czechslovak

      - name: Clean previous build files
        run: rm -f presentation/*.pdf presentation/*.aux presentation/*.log

      - name: Compile Beamer Presentation
        run: |
          pdflatex -file-line-error -output-directory=presentation presentation/prezentace.tex
          pdflatex -file-line-error -output-directory=presentation presentation/prezentace.tex

      - name: Create release with compiled presentation
        uses: softprops/action-gh-release@v2
        with:
          files: presentation/prezentace.pdf
